### PR TITLE
Purescript 0.9.1 update

### LINKED ISSUE #7: Purescript 0.9.1 update
I'm going to work on the PR

### PR DESCRIPTION
**Pull request by kika**
WIP: the bower.json contains a link to my own repository for `purescript-node-process` which I'll replace with appropriate version as soon as `purescript-node-process` will be merged.

Fixes #7

### CODE REVIEW

**Comment by paf31** [comment]
LGTM!

**Comment by hdgarrood** [comment]
I usually prefer spaces either side of the `::` in type signatures, but I'm not too fussed about that. LGTM too; I think bower.json can be updated to depend on node-process ^1.0.0 now, so if you do that I'll merge and tag. Thanks!

**Comment by kika** [comment]
Done. 

Speaking of spaces - I'm a nasty cheater, I save spaces to fit more code into one punch card and use ligatures for it to look good.
image

**Comment by paf31** [comment]
I'll tag this now, thanks!

**Pull request merged**
