### PR TITLE
Added close function.

### PR DESCRIPTION
**Pull request by AphonicChaos**
Unless I missed something, there wasn't a way to close an interface other than to Ctrl+c.

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Thanks!

**Comment by AphonicChaos** [comment]
~~@paf31 do I need to version bump this, or is that done on your end?~~ NVM, I see there are merge conflicts.

**Comment by paf31** [comment]
Oh sorry I thought I merged this.

**Comment by AphonicChaos** [comment]
No worries. Ended up needing to update things. Stylistically, would you prefer the redundant `do`s stayed in for consistency of formatting? I tend to only use them when they are absolutely necessary.

**Comment by paf31** [comment]
No I think this looks great, thanks!

**Pull request merged**
